import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, browserLocalPersistence, setPersistence, signInWithEmailAndPassword, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, deleteDoc, updateDoc, setDoc, getDocs, writeBatch, onSnapshot } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js?v=20260816-4";

if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./service-worker.js"));

["gesturestart", "gesturechange", "gestureend"].forEach((eventName) => document.addEventListener(eventName, (event) => event.preventDefault(), { passive: false }));
document.addEventListener("touchmove", (event) => { if (event.touches.length > 1) event.preventDefault(); }, { passive: false });

const FAMILY = ["families", "default"];
const LEGACY_KEY = "shopping-list";
const MIGRATION_KEY = "shopping-list-firebase-imported";
const USERS = {
  thomi: { name: "Thomi", email: "thomi@lista-familiar.app", monthly: false },
  mati: { name: "Mati", email: "mati@lista-familiar.app", monthly: true },
  delfi: { name: "Delfi", email: "delfi@lista-familiar.app", monthly: true },
  mama: { name: "Mamá", email: "mama@lista-familiar.app", monthly: true },
};
const INDIVIDUAL_ACCOUNTS = {
  delfi: { expenses: "delfiIndividualExpenses", budgets: "delfiIndividualBudgets" },
  mama: { expenses: "mamaIndividualExpenses", budgets: "mamaIndividualBudgets" },
};
const CATEGORIES = ["Almacén", "Limpieza", "Frutas y Verduras", "Carnes", "Lácteos", "Bebidas", "Higiene", "Otros"];
const RULES = [
  ["Frutas y Verduras", "banana manzana naranja mandarina limon papa batata cebolla tomate lechuga zanahoria morron pimiento zapallo calabaza brocoli espinaca palta ajo frutilla uva"],
  ["Carnes", "carne pollo pescado milanesa chorizo hamburguesa salchicha bondiola cerdo asado"],
  ["Lácteos", "leche queso yogur manteca crema huevo"],
  ["Bebidas", "agua gaseosa jugo cerveza vino soda bebida energizante"],
  ["Limpieza", "detergente lavandina desinfectante limpiador esponja trapo bolsa basura papel cocina suavizante"],
  ["Higiene", "shampoo acondicionador desodorante dentifrico pasta cepillo higienico jabon toallita tampon afeitadora"],
  ["Almacén", "arroz fideo pasta harina azucar sal aceite vinagre salsa lata atun lenteja garbanzo avena cereal galleta pan cafe te yerba mermelada mayonesa ketchup condimento pure"],
].map(([category, words]) => ({ category, words: words.split(" ") }));
const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", minimumFractionDigits: 2 });
const dateFormat = new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "2-digit", year: "numeric" });
const q = (id) => document.querySelector(`#${id}`);
const el = {
  userSwitcher:q("user-switcher"), userMenu:q("user-menu"), activeUserLabel:q("active-user-label"), dialog:q("access-dialog"), selection:q("user-selection"), selectionCancel:q("user-selection-cancel"), accessForm:q("access-form"), accessDescription:q("access-dialog-description"), accessCode:q("access-code"), toggleAccessCode:q("toggle-access-code"), accessError:q("access-error"), accessCancel:q("access-cancel"), confirmDialog:q("confirm-dialog"), confirmDescription:q("confirm-dialog-description"), confirmAccept:q("confirm-accept"), confirmCancel:q("confirm-cancel"),
  eyebrow:q("header-eyebrow"), title:q("header-title"), subtitle:q("header-subtitle"),
  productForm:q("product-form"), productName:q("product-name"), productError:q("product-error"), productsList:q("products-list"), productsCount:q("products-count"), productsSummary:q("products-summary"), clearProducts:q("clear-products"),
  tabs:q("app-tabs"), productsTab:q("tab-products"), expensesTab:q("tab-expenses"), extraTab:q("tab-extra-expenses"), individualTab:q("tab-individual-expenses"), productsPanel:q("products-panel"), expensesPanel:q("expenses-panel"), extraPanel:q("extra-expenses-panel"), individualPanel:q("individual-expenses-panel"),
  expenseForm:q("expense-form"), expenseDate:q("expense-date"), expenseStore:q("expense-store"), expenseAmount:q("expense-amount"), expenseError:q("expense-error"), expensesList:q("expenses-list"), expensesEmpty:q("expenses-empty"), expensesWrap:q("expenses-table-wrap"), expensesTotal:q("expenses-total"), expensesTotalLabel:q("expenses-total-label"), expensesSummary:q("expenses-summary"), expenseMonth:q("expense-month-filter"), expensesEmptyTitle:q("expenses-empty-title"), expensesEmptyDescription:q("expenses-empty-description"), clearExpenses:q("clear-expenses"),
  extraForm:q("extra-expense-form"), extraDate:q("extra-expense-date"), extraDetail:q("extra-expense-detail"), extraAmount:q("extra-expense-amount"), extraSubmit:q("extra-expense-submit"), extraError:q("extra-expense-error"), extraPermission:q("extra-expense-permission"), extraList:q("extra-expenses-list"), extraEmpty:q("extra-expenses-empty"), extraWrap:q("extra-expenses-table-wrap"), extraTotal:q("extra-expenses-total"), extraTotalLabel:q("extra-expenses-total-label"), extraSummary:q("extra-expenses-summary"), extraMonth:q("extra-expense-month-filter"), extraEmptyTitle:q("extra-expenses-empty-title"), extraEmptyDescription:q("extra-expenses-empty-description"), clearExtra:q("clear-extra-expenses"), budgetForm:q("monthly-budget-form"), budgetLabel:q("monthly-budget-label"), budgetAmount:q("monthly-budget-amount"), budgetSubmit:q("monthly-budget-submit"), budgetCancel:q("monthly-budget-cancel"), budgetEdit:q("monthly-budget-edit"), budgetError:q("monthly-budget-error"), availableCard:q("monthly-available-card"), availableLabel:q("monthly-available-label"), availableAmount:q("monthly-available"), availableHint:q("monthly-available-hint"),
  individualForm:q("individual-expense-form"), individualDate:q("individual-expense-date"), individualDetail:q("individual-expense-detail"), individualAmount:q("individual-expense-amount"), individualError:q("individual-expense-error"), individualList:q("individual-expenses-list"), individualEmpty:q("individual-expenses-empty"), individualWrap:q("individual-expenses-table-wrap"), individualTotal:q("individual-expenses-total"), individualTotalLabel:q("individual-expenses-total-label"), individualSummary:q("individual-expenses-summary"), individualMonth:q("individual-expense-month-filter"), individualEmptyTitle:q("individual-expenses-empty-title"), clearIndividual:q("clear-individual-expenses"), individualBudgetForm:q("individual-budget-form"), individualBudgetLabel:q("individual-budget-label"), individualBudgetAmount:q("individual-budget-amount"), individualBudgetSubmit:q("individual-budget-submit"), individualBudgetCancel:q("individual-budget-cancel"), individualBudgetEdit:q("individual-budget-edit"), individualBudgetError:q("individual-budget-error"), individualAvailableCard:q("individual-available-card"), individualAvailableLabel:q("individual-available-label"), individualAvailableAmount:q("individual-available"), individualAvailableHint:q("individual-available-hint"),
};
const auth = getAuth(initializeApp(firebaseConfig));
const db = getFirestore();
let user = null, userId = null, pending = null, unsubs = [];
let state = { faltantes: [], gastos: [], gastosExtra: [], gastosIndividuales: [], presupuestos: {}, presupuestosIndividuales: {}, categorias: {} };
let expenseMonth = monthKey(today()), extraMonth = monthKey(today()), individualMonth = monthKey(today());
let editingBudget = false;
let editingIndividualBudget = false;

el.expenseDate.value = today(); el.extraDate.value = today(); el.individualDate.value = today(); bind(); render();
setPersistence(auth, browserLocalPersistence).catch(console.warn);
onAuthStateChanged(auth, async (session) => { editingBudget = false; editingIndividualBudget = false; user = session; userId = session ? Object.keys(USERS).find((id) => USERS[id].email === session.email) || null : null; if (userId) { subscribe(); render(); await migrate(); } else { stop(); state = { faltantes: [], gastos: [], gastosExtra: [], gastosIndividuales: [], presupuestos: {}, presupuestosIndividuales: {}, categorias: {} }; } render(); });

function bind() {
  el.userSwitcher.onclick = openUserMenu; el.userMenu.onclick = chooseUser; el.accessForm.onsubmit = login; el.accessCancel.onclick = closeDialog; el.selectionCancel.onclick = closeDialog; el.toggleAccessCode.onclick = togglePassword;
  el.dialog.addEventListener("close", () => { pending = null; el.selection.hidden = false; el.accessForm.hidden = true; });
  const tabs = [[el.productsTab,"products"],[el.expensesTab,"expenses"],[el.extraTab,"extra"],[el.individualTab,"individual"]];
  tabs.forEach(([button, tab]) => {
    button.onclick = () => selectTab(tab);
    button.onkeydown = (event) => {
      if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return;
      event.preventDefault();
      const visibleTabs=tabs.filter(([candidate])=>!candidate.hidden),index=visibleTabs.findIndex(([candidate])=>candidate===button),next=event.key==='Home'?0:event.key==='End'?visibleTabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+visibleTabs.length)%visibleTabs.length;
      selectTab(visibleTabs[next][1]);
      visibleTabs[next][0].focus();
    };
  });
  el.productForm.onsubmit = addProduct; el.productsList.onclick = removeProduct; el.productsList.onchange = changeCategory; el.clearProducts.onclick = clearProducts;
  el.expenseForm.onsubmit = addSuper; el.expensesList.onclick = removeSuper; el.clearExpenses.onclick = clearSupers; el.expenseMonth.onchange = () => { expenseMonth = el.expenseMonth.value; renderExpenses(); };
  el.extraForm.onsubmit = addExtra; el.extraList.onclick = removeExtra; el.clearExtra.onclick = clearExtras; el.extraMonth.onchange = () => { editingBudget = false; extraMonth = el.extraMonth.value; renderExtra(); };
  el.budgetForm.onsubmit = saveMonthlyBudget;
  el.budgetEdit.onclick = editMonthlyBudget;
  el.budgetCancel.onclick = cancelMonthlyBudget;
  el.individualForm.onsubmit = addIndividual; el.individualList.onclick = removeIndividual; el.clearIndividual.onclick = clearIndividuals; el.individualMonth.onchange = () => { editingIndividualBudget = false; individualMonth = el.individualMonth.value; renderIndividual(); };
  el.individualBudgetForm.onsubmit = saveIndividualBudget;
  el.individualBudgetEdit.onclick = editIndividualBudget;
  el.individualBudgetCancel.onclick = cancelIndividualBudget;
  [[el.productName,el.productError],[el.expenseDate,el.expenseError],[el.expenseStore,el.expenseError],[el.extraDate,el.extraError],[el.extraDetail,el.extraError],[el.individualDate,el.individualError],[el.individualDetail,el.individualError]].forEach(([input,message]) => input.oninput = () => clearError(input,message));
  [[el.expenseAmount,el.expenseError],[el.extraAmount,el.extraError],[el.budgetAmount,el.budgetError],[el.individualAmount,el.individualError],[el.individualBudgetAmount,el.individualBudgetError]].forEach(([input,message]) => input.oninput = () => { input.value = amountTyping(input.value); clearError(input,message); });
  el.accessCode.oninput = () => clearError(el.accessCode, el.accessError);
}
function subscribe() {
  stop();
  state.gastosIndividuales = []; state.presupuestosIndividuales = {};
  const watch = (name,key,onError=syncError) => onSnapshot(collection(db,...FAMILY,name), (snap) => { state[key] = snap.docs.map((d) => ({ id:d.id,...d.data() })); render(); }, onError);
  unsubs = [watch("products","faltantes"), watch("superExpenses","gastos"), watch("monthlyExpenses","gastosExtra")];
  unsubs.push(onSnapshot(doc(db,...FAMILY,"meta","categories"), (snap) => { state.categorias = snap.exists() ? snap.data().items || {} : {}; renderProducts(); }, syncError));
  unsubs.push(onSnapshot(doc(db,...FAMILY,"meta","monthlyBudgets"), (snap) => { state.presupuestos = snap.exists() ? snap.data().items || {} : {}; renderExtra(); }, syncError));
  const individual=individualAccount();
  if(individual){
    unsubs.push(watch(individual.expenses,"gastosIndividuales",individualSyncError));
    unsubs.push(onSnapshot(doc(db,...FAMILY,"meta",individual.budgets), (snap) => { state.presupuestosIndividuales = snap.exists() ? snap.data().items || {} : {}; renderIndividual(); }, individualSyncError));
  }
}
function stop() { unsubs.forEach((fn) => fn()); unsubs = []; }
function syncError(error) { console.error(error); el.productError.textContent = "No se pudo sincronizar. Revisá la conexión e ingresá otra vez."; }
function individualSyncError(error) { console.error(error); el.individualError.textContent = "No se pudieron sincronizar los gastos individuales. Revisá la conexión y los permisos de Firebase."; }
function isLogged() { return Boolean(user && userId); }
function nameOf(id) { return USERS[id]?.name || "Usuario"; }
function individualAccount() { return INDIVIDUAL_ACCOUNTS[userId] || null; }

function openUserMenu() { el.selection.hidden=false; el.accessForm.hidden=true; if (!el.dialog.open) el.dialog.showModal(); }
function chooseUser(event) { const button=event.target.closest("button[data-user-id]"); if (!button || !USERS[button.dataset.userId]) return; pending=button.dataset.userId; el.accessCode.value=""; el.accessDescription.textContent=`Ingresá el código de acceso de ${nameOf(pending)} para continuar.`; el.selection.hidden=true; el.accessForm.hidden=false; el.accessCode.focus(); }
async function login(event) { event.preventDefault(); if (!pending) return; try { await signInWithEmailAndPassword(auth, USERS[pending].email, el.accessCode.value.trim()); closeDialog(); } catch (reason) { console.warn(reason); const message = reason.code === "auth/unauthorized-domain" ? "Falta autorizar esta dirección en Firebase." : reason.code === "auth/too-many-requests" ? "Hubo muchos intentos. Esperá unos minutos y probá de nuevo." : "La contraseña es incorrecta."; error(el.accessCode,el.accessError,message); } }
function closeDialog() { if (el.dialog.open) el.dialog.close(); }
function togglePassword() { const visible = el.accessCode.type === "text"; el.accessCode.type = visible ? "password" : "text"; el.toggleAccessCode.textContent = visible ? "Ver" : "Ocultar"; el.toggleAccessCode.setAttribute("aria-label", visible ? "Mostrar contraseña" : "Ocultar contraseña"); }

function selectTab(tab) { if(tab==="individual"&&!individualAccount())tab="products";const info={products:[el.productsTab,el.productsPanel,"Para la próxima compra","Productos faltantes","Agregá lo que necesitás para tu próxima compra."],expenses:[el.expensesTab,el.expensesPanel,"Historial de compras","Gastos súper","Registrá y consultá las compras del supermercado."],extra:[el.extraTab,el.extraPanel,"Control mensual","Gastos mensuales","Llevá el detalle de tus gastos fuera del supermercado."],individual:[el.individualTab,el.individualPanel,"Control personal","Gastos individuales","Tu espacio privado para controlar los gastos personales."]}; Object.entries(info).forEach(([key,[button,panel]])=>{const on=key===tab; button.classList.toggle("is-active",on); button.setAttribute("aria-selected",on); button.tabIndex=on?0:-1; panel.hidden=!on;}); const [, ,eyebrow,title,subtitle]=info[tab]; el.eyebrow.textContent=eyebrow;el.title.textContent=title;el.subtitle.textContent=subtitle; }

async function addProduct(event) { event.preventDefault(); const nombre=el.productName.value.trim(); if (!isLogged()) return error(el.productName,el.productError,"Elegí tu usuario antes de agregar un producto."); if (!nombre) return error(el.productName,el.productError,"Escribí el nombre del producto antes de agregarlo."); const normalizedName=norm(nombre); if (state.faltantes.some((p)=>norm(p.nombre)===normalizedName)) return error(el.productName,el.productError,`“${nombre}” ya está en la lista. No se agregó un producto repetido.`); const category=categorize(nombre); try { await setDoc(doc(db,...FAMILY,"products",encodeURIComponent(normalizedName)),{nombre,categoria:category.categoria,requiereCategoria:category.requiereCategoria}); el.productName.value="";clearError(el.productName,el.productError);el.productName.focus(); } catch { writeError(el.productName,el.productError); } }
function categorize(nombre) { const n=norm(nombre); if (CATEGORIES.includes(state.categorias[n])) return {categoria:state.categorias[n],requiereCategoria:false}; const found=RULES.find((rule)=>rule.words.some((word)=>n.includes(word))); return found ? {categoria:found.category,requiereCategoria:false}:{categoria:"Otros",requiereCategoria:true}; }
async function removeProduct(event) { const button=event.target.closest("button[data-product-id]"); if(button) await remove("products",button.dataset.productId,el.productError); }
async function clearProducts() { if(state.faltantes.length && await confirmAction("¿Querés eliminar todos los productos faltantes? Esta acción no se puede deshacer.", "Limpiar lista")) await removeMany("products",state.faltantes.map((p)=>p.id),el.productError); }
async function changeCategory(event) { const select=event.target.closest("select[data-product-id]"); if(!select||!CATEGORIES.includes(select.value))return; const product=state.faltantes.find((p)=>p.id===select.dataset.productId);if(!product)return;try{await Promise.all([updateDoc(doc(db,...FAMILY,"products",product.id),{categoria:select.value,requiereCategoria:false}),setDoc(doc(db,...FAMILY,"meta","categories"),{items:{...state.categorias,[norm(product.nombre)]:select.value}})]);}catch{writeError(select,el.productError);} }

async function addSuper(event) { event.preventDefault(); const fecha=el.expenseDate.value,supermercado=el.expenseStore.value.trim(),monto=parseAmount(el.expenseAmount.value); if(!isLogged())return error(el.expenseStore,el.expenseError,"Elegí tu usuario antes de cargar una compra."); if(!fecha)return error(el.expenseDate,el.expenseError,"Seleccioná la fecha de la compra.");if(!supermercado)return error(el.expenseStore,el.expenseError,"Escribí el nombre del supermercado.");if(!Number.isFinite(monto)||monto<=0)return error(el.expenseAmount,el.expenseError,"Ingresá un monto mayor que cero.");try{await addDoc(collection(db,...FAMILY,"superExpenses"),{fecha,supermercado,monto,usuarioId:userId,ownerUid:user.uid,createdAt:Date.now()});expenseMonth=monthKey(fecha);el.expenseStore.value="";el.expenseAmount.value="";el.expenseDate.value=today();clearError(el.expenseStore,el.expenseError);el.expenseStore.focus();}catch{writeError(el.expenseStore,el.expenseError);} }
async function removeSuper(event) {const button=event.target.closest("button[data-expense-id]");if(button)await remove("superExpenses",button.dataset.expenseId,el.expenseError);}
async function clearSupers(){const own=state.gastos.filter((x)=>x.ownerUid===user?.uid);if(own.length&&await confirmAction("¿Querés eliminar tus compras del súper? Las compras de los demás usuarios se conservarán.", "Limpiar compras"))await removeMany("superExpenses",own.map((x)=>x.id),el.expenseError);}
async function addExtra(event){event.preventDefault();const fecha=el.extraDate.value,detalle=el.extraDetail.value.trim(),monto=parseAmount(el.extraAmount.value);if(!isLogged())return error(el.extraDetail,el.extraError,"Elegí tu usuario antes de cargar un gasto.");if(!USERS[userId].monthly)return;if(!fecha)return error(el.extraDate,el.extraError,"Seleccioná la fecha del gasto.");if(!detalle)return error(el.extraDetail,el.extraError,"Escribí un detalle para identificar el gasto.");if(!Number.isFinite(monto)||monto<=0)return error(el.extraAmount,el.extraError,"Ingresá un monto mayor que cero.");try{await addDoc(collection(db,...FAMILY,"monthlyExpenses"),{fecha,detalle,monto,usuarioId:userId,ownerUid:user.uid,createdAt:Date.now()});extraMonth=monthKey(fecha);el.extraDetail.value="";el.extraAmount.value="";el.extraDate.value=today();clearError(el.extraDetail,el.extraError);el.extraDetail.focus();}catch{writeError(el.extraDetail,el.extraError);}}
async function removeExtra(event){const button=event.target.closest("button[data-extra-expense-id]");if(button)await remove("monthlyExpenses",button.dataset.extraExpenseId,el.extraError);}
async function clearExtras(){const own=state.gastosExtra.filter((x)=>x.ownerUid===user?.uid);if(own.length&&await confirmAction("¿Querés eliminar tus gastos mensuales cargados manualmente? Los gastos de los demás usuarios y las compras del súper se conservarán.", "Limpiar gastos"))await removeMany("monthlyExpenses",own.map((x)=>x.id),el.extraError);}
async function saveMonthlyBudget(event){event.preventDefault();const monto=parseAmount(el.budgetAmount.value);if(userId!=="thomi")return error(el.budgetAmount,el.budgetError,"Solo Thomi puede definir o modificar el dinero disponible.");if(!Number.isFinite(monto)||monto<0)return error(el.budgetAmount,el.budgetError,"Ingresá un monto válido, igual o mayor que cero.");try{const record={monto,usuarioId:userId,ownerUid:user.uid,updatedAt:Date.now()};await setDoc(doc(db,...FAMILY,"meta","monthlyBudgets"),{items:{[extraMonth]:record}},{merge:true});state.presupuestos={...state.presupuestos,[extraMonth]:record};editingBudget=false;clearError(el.budgetAmount,el.budgetError);renderExtra();}catch{writeError(el.budgetAmount,el.budgetError);}}
function editMonthlyBudget(){if(userId!=="thomi")return;editingBudget=true;renderExtra();requestAnimationFrame(()=>{el.budgetAmount.focus();el.budgetAmount.select();});}
function cancelMonthlyBudget(){editingBudget=false;clearError(el.budgetAmount,el.budgetError);renderExtra();}
async function addIndividual(event){event.preventDefault();const account=individualAccount(),fecha=el.individualDate.value,detalle=el.individualDetail.value.trim(),monto=parseAmount(el.individualAmount.value);if(!account)return error(el.individualDetail,el.individualError,"Esta sección es privada.");if(!fecha)return error(el.individualDate,el.individualError,"Seleccioná la fecha del gasto.");if(!detalle)return error(el.individualDetail,el.individualError,"Escribí un detalle para identificar el gasto.");if(!Number.isFinite(monto)||monto<=0)return error(el.individualAmount,el.individualError,"Ingresá un monto mayor que cero.");try{await addDoc(collection(db,...FAMILY,account.expenses),{fecha,detalle,monto,usuarioId:userId,ownerUid:user.uid,createdAt:Date.now()});individualMonth=monthKey(fecha);el.individualDetail.value="";el.individualAmount.value="";el.individualDate.value=today();clearError(el.individualDetail,el.individualError);el.individualDetail.focus();}catch{writeError(el.individualDetail,el.individualError);}}
async function removeIndividual(event){const account=individualAccount(),button=event.target.closest("button[data-individual-expense-id]");if(button&&account)await remove(account.expenses,button.dataset.individualExpenseId,el.individualError);}
async function clearIndividuals(){const account=individualAccount();if(!account)return;const own=state.gastosIndividuales.filter((x)=>x.ownerUid===user?.uid);if(own.length&&await confirmAction("¿Querés eliminar todos tus gastos individuales? Esta acción no se puede deshacer.","Limpiar gastos"))await removeMany(account.expenses,own.map((x)=>x.id),el.individualError);}
async function saveIndividualBudget(event){event.preventDefault();const account=individualAccount(),monto=parseAmount(el.individualBudgetAmount.value);if(!account)return error(el.individualBudgetAmount,el.individualBudgetError,"Esta sección es privada.");if(!Number.isFinite(monto)||monto<0)return error(el.individualBudgetAmount,el.individualBudgetError,"Ingresá un monto válido, igual o mayor que cero.");try{const record={monto,usuarioId:userId,ownerUid:user.uid,updatedAt:Date.now()};await setDoc(doc(db,...FAMILY,"meta",account.budgets),{items:{[individualMonth]:record}},{merge:true});state.presupuestosIndividuales={...state.presupuestosIndividuales,[individualMonth]:record};editingIndividualBudget=false;clearError(el.individualBudgetAmount,el.individualBudgetError);renderIndividual();}catch{writeError(el.individualBudgetAmount,el.individualBudgetError);}}
function editIndividualBudget(){if(!individualAccount())return;editingIndividualBudget=true;renderIndividual();requestAnimationFrame(()=>{el.individualBudgetAmount.focus();el.individualBudgetAmount.select();});}
function cancelIndividualBudget(){editingIndividualBudget=false;clearError(el.individualBudgetAmount,el.individualBudgetError);renderIndividual();}
async function remove(collectionName,id,message){try{await deleteDoc(doc(db,...FAMILY,collectionName,id));}catch{message.textContent="Solo puede eliminarlo la persona que lo cargó.";}}
async function removeMany(collectionName,ids,message){try{const batch=writeBatch(db);ids.forEach((id)=>batch.delete(doc(db,...FAMILY,collectionName,id)));await batch.commit();}catch{message.textContent="No se pudieron eliminar los registros.";}}

function render(){renderUser();renderProducts();renderExpenses();renderExtra();renderIndividual();}
function renderUser(){const hasIndividual=Boolean(individualAccount());el.activeUserLabel.textContent=isLogged()?nameOf(userId):"Elegí usuario";el.userMenu.querySelectorAll("button[data-user-id]").forEach((button)=>button.setAttribute("aria-current",button.dataset.userId===userId));el.individualTab.hidden=!hasIndividual;el.tabs.classList.toggle("has-individual",hasIndividual);if(!hasIndividual&&el.individualTab.classList.contains("is-active"))selectTab("products");}
function renderProducts(){el.productsList.replaceChildren();el.productsCount.textContent=state.faltantes.length;el.productsSummary.textContent=state.faltantes.length?`Tenés ${state.faltantes.length} productos pendientes.`:"Tu lista está vacía.";el.clearProducts.disabled=!state.faltantes.length;if(!state.faltantes.length){el.productsList.append(html('<div class="empty-state"><span class="empty-icon">✓</span><strong>La lista está al día</strong><p>Agregá un producto y su categoría aparecerá automáticamente.</p></div>'));return;}CATEGORIES.forEach((category)=>{const products=state.faltantes.filter((p)=>p.categoria===category);if(products.length)el.productsList.append(categoryGroup(category,products));});}
function categoryGroup(category,products){const section=html(`<section class="category-group"><div class="category-header"><h3 class="category-title"><span class="category-dot"></span><span>${category}</span></h3><span class="category-quantity">${products.length===1?"1 producto":`${products.length} productos`}</span></div></section>`);const list=document.createElement("ul");list.className="product-items";products.forEach((product)=>{const item=document.createElement("li");item.className="product-item";const title=document.createElement("span");title.className="product-name";title.textContent=product.nombre;const actions=document.createElement("div");actions.className="product-actions";if(product.requiereCategoria){const select=document.createElement("select");select.className="product-category-select";select.dataset.productId=product.id;select.append(option("Elegir categoría","",true),...CATEGORIES.map((c)=>option(c,c)));actions.append(select);}const button=document.createElement("button");button.type="button";button.className="remove-button";button.dataset.productId=product.id;button.textContent="Quitar";actions.append(button);item.append(title,actions);list.append(item);});section.append(list);return section;}
function renderExpenses(){const months=monthsFor(state.gastos);if(!months.includes(expenseMonth))expenseMonth=monthKey(today());monthOptions(el.expenseMonth,months,expenseMonth);const items=itemsFor(state.gastos,expenseMonth);tableState(items,el.expensesList,el.expensesEmpty,el.expensesWrap,el.expensesTotal,el.expensesTotalLabel,el.expensesSummary,el.expensesEmptyTitle,el.expensesEmptyDescription,expenseMonth,"Cuando cargues una compra, vas a verla acá.",false);el.clearExpenses.disabled=!state.gastos.some((x)=>x.ownerUid===user?.uid);}
function renderExtra(){const all=[...state.gastosExtra,...state.gastos.map((x)=>({...x,origen:"super",detalle:`Compra de súper: ${x.supermercado}`}))];const months=[...new Set([...monthsFor(all),...Object.keys(state.presupuestos).filter((id)=>/^\d{4}-\d{2}$/.test(id))])].sort();if(!months.includes(extraMonth))extraMonth=monthKey(today());monthOptions(el.extraMonth,months,extraMonth);const items=itemsFor(all,extraMonth);tableState(items,el.extraList,el.extraEmpty,el.extraWrap,el.extraTotal,el.extraTotalLabel,el.extraSummary,el.extraEmptyTitle,el.extraEmptyDescription,extraMonth,"Cuando cargues un gasto, vas a verlo acá.",true);renderMonthlyBudget(items);const enabled=Boolean(userId&&USERS[userId].monthly);[el.extraDate,el.extraDetail,el.extraAmount,el.extraSubmit].forEach((input)=>input.disabled=!enabled);el.extraPermission.hidden=enabled;el.extraPermission.textContent=enabled?"":userId==="thomi"?"Thomi solo puede cargar productos faltantes y gastos del súper.":"Elegí un usuario para poder cargar gastos mensuales.";el.clearExtra.disabled=!state.gastosExtra.some((x)=>x.ownerUid===user?.uid);}
function renderMonthlyBudget(items){const record=state.presupuestos[extraMonth],hasBudget=Number.isFinite(Number(record?.monto)),isThomi=userId==="thomi",showForm=isThomi&&(!hasBudget||editingBudget),budget=hasBudget?Number(record.monto):0,spent=items.reduce((sum,x)=>sum+x.monto,0),available=hasBudget?budget-spent:0,label=monthLabel(extraMonth);el.budgetForm.hidden=!showForm;el.budgetEdit.hidden=!(isThomi&&hasBudget&&!editingBudget);el.budgetCancel.hidden=!(hasBudget&&editingBudget);el.budgetSubmit.textContent=hasBudget?"Guardar cambios":"Guardar";el.budgetLabel.textContent=`Dinero para ${label}`;el.availableLabel.textContent=`Disponible en ${label}`;el.availableAmount.textContent=money.format(available);el.availableHint.textContent=!hasBudget?(isThomi?"Definí el dinero del mes":"Thomi todavía no definió el dinero del mes"):available<0?"Superaste el dinero disponible":"Luego de restar todos los gastos";el.extraTotalLabel.textContent=`Total gastado en ${label}`;el.availableCard.classList.toggle("is-negative",hasBudget&&available<0);el.budgetSubmit.disabled=!isThomi;if(document.activeElement!==el.budgetAmount)el.budgetAmount.value=hasBudget?amountForInput(budget):"";}
function renderIndividual(){const hasIndividual=Boolean(individualAccount()),months=[...new Set([...monthsFor(state.gastosIndividuales),...Object.keys(state.presupuestosIndividuales).filter((id)=>/^\d{4}-\d{2}$/.test(id))])].sort();if(!months.includes(individualMonth))individualMonth=monthKey(today());monthOptions(el.individualMonth,months,individualMonth);const items=hasIndividual?itemsFor(state.gastosIndividuales,individualMonth):[],label=monthLabel(individualMonth),total=items.reduce((sum,x)=>sum+x.monto,0);el.individualTotal.textContent=money.format(total);el.individualTotalLabel.textContent=`Total gastado en ${label}`;el.individualSummary.textContent=items.length?`Tenés ${items.length===1?"1 gasto individual registrado":`${items.length} gastos individuales registrados`} en ${label}.`:`No hay gastos individuales registrados en ${label}.`;el.individualEmpty.hidden=Boolean(items.length);el.individualWrap.hidden=!items.length;el.individualEmptyTitle.textContent=`Sin gastos individuales en ${label}`;el.individualList.replaceChildren(...items.map(individualRow));el.clearIndividual.disabled=!hasIndividual||!state.gastosIndividuales.length;[el.individualDate,el.individualDetail,el.individualAmount].forEach((input)=>input.disabled=!hasIndividual);renderIndividualBudget(items);}
function renderIndividualBudget(items){const record=state.presupuestosIndividuales[individualMonth],hasBudget=Number.isFinite(Number(record?.monto)),hasIndividual=Boolean(individualAccount()),showForm=hasIndividual&&(!hasBudget||editingIndividualBudget),budget=hasBudget?Number(record.monto):0,spent=items.reduce((sum,x)=>sum+x.monto,0),available=hasBudget?budget-spent:0,label=monthLabel(individualMonth);el.individualBudgetForm.hidden=!showForm;el.individualBudgetEdit.hidden=!(hasIndividual&&hasBudget&&!editingIndividualBudget);el.individualBudgetCancel.hidden=!(hasBudget&&editingIndividualBudget);el.individualBudgetSubmit.textContent=hasBudget?"Guardar cambios":"Guardar";el.individualBudgetLabel.textContent=`Dinero para ${label}`;el.individualAvailableLabel.textContent=`Disponible en ${label}`;el.individualAvailableAmount.textContent=money.format(available);el.individualAvailableHint.textContent=!hasBudget?"Definí el dinero del mes":available<0?"Superaste el dinero disponible":"Luego de restar tus gastos individuales";el.individualAvailableCard.classList.toggle("is-negative",hasBudget&&available<0);el.individualBudgetSubmit.disabled=!hasIndividual;if(document.activeElement!==el.individualBudgetAmount)el.individualBudgetAmount.value=hasBudget?amountForInput(budget):"";}
function tableState(items,list,empty,wrap,total,totalLabel,summary,emptyTitle,emptyDescription,month,emptyText,monthly){const countText=monthly?(items.length===1?"1 gasto mensual registrado":`${items.length} gastos mensuales registrados`):(items.length===1?"1 compra registrada":`${items.length} compras registradas`);total.textContent=money.format(items.reduce((sum,x)=>sum+x.monto,0));totalLabel.textContent=`Total de ${monthLabel(month)}`;summary.textContent=items.length?`Tenés ${countText} en ${monthLabel(month)}.`:monthly?`No hay gastos mensuales registrados en ${monthLabel(month)}.`:`No hay compras registradas en ${monthLabel(month)}.`;empty.hidden=Boolean(items.length);wrap.hidden=!items.length;emptyTitle.textContent=`Sin gastos en ${monthLabel(month)}`;emptyDescription.textContent=emptyText;list.replaceChildren(...items.map((x)=>monthly?extraRow(x):superRow(x)));}
function superRow(x){return row(x,x.supermercado,"expenseId",false);}
function extraRow(x){return row(x,x.detalle,"extraExpenseId",x.origen==="super");}
function individualRow(x){const tr=document.createElement("tr");tr.append(cell(formatDate(x.fecha),"Fecha","date-cell"),cell(x.detalle,"Detalle","store-cell"),cell(money.format(x.monto),"Monto","amount-cell"));const action=cell("","","action-cell");if(x.ownerUid===user?.uid){const button=document.createElement("button");button.type="button";button.className="remove-button";button.dataset.individualExpenseId=x.id;button.textContent="Eliminar";action.append(button);}tr.append(action);return tr;}
function row(x,detail,key,linked){const tr=document.createElement("tr");tr.append(cell(formatDate(x.fecha),"Fecha","date-cell"),cell(detail,"Detalle","store-cell"),cell(nameOf(x.usuarioId),"Cargó"),cell(money.format(x.monto),"Monto","amount-cell"));const action=cell("","","action-cell");if(linked){const note=html('<span class="source-note">Se gestiona en Gastos súper</span>');action.append(note);}else if(x.ownerUid===user?.uid){const button=document.createElement("button");button.type="button";button.className="remove-button";button.dataset[key]=x.id;button.textContent="Eliminar";action.append(button);}tr.append(action);return tr;}

async function migrate(){if(userId!=="thomi"||localStorage.getItem(MIGRATION_KEY))return;let legacy;try{legacy=JSON.parse(localStorage.getItem(LEGACY_KEY));}catch{return;}if(!legacy||!Array.isArray(legacy.faltantes)||!Array.isArray(legacy.gastos))return;const existing=await getDocs(collection(db,...FAMILY,"products"));if(existing.size||(!legacy.faltantes.length&&!legacy.gastos.length)){localStorage.setItem(MIGRATION_KEY,"true");return;}if(!await confirmAction("Encontré datos guardados en este celular. ¿Querés importarlos una única vez a la lista familiar?", "Importar datos"))return;try{const batch=writeBatch(db);legacy.faltantes.forEach((x)=>batch.set(doc(collection(db,...FAMILY,"products")),{nombre:x.nombre,categoria:x.categoria,requiereCategoria:Boolean(x.requiereCategoria)}));legacy.gastos.forEach((x)=>batch.set(doc(collection(db,...FAMILY,"superExpenses")),{fecha:x.fecha,supermercado:x.supermercado,monto:x.monto,usuarioId:USERS[x.usuarioId]?x.usuarioId:"thomi",ownerUid:user.uid,createdAt:Date.now()}));(legacy.gastosExtra||[]).filter((x)=>x.origen!=="super").forEach((x)=>batch.set(doc(collection(db,...FAMILY,"monthlyExpenses")),{fecha:x.fecha,detalle:x.detalle,monto:x.monto,usuarioId:USERS[x.usuarioId]?x.usuarioId:"thomi",ownerUid:user.uid,createdAt:Date.now()}));if(legacy.categoriasPersonalizadas&&Object.keys(legacy.categoriasPersonalizadas).length)batch.set(doc(db,...FAMILY,"meta","categories"),{items:legacy.categoriasPersonalizadas});await batch.commit();localStorage.setItem(MIGRATION_KEY,"true");}catch(error){console.warn(error);}}
function itemsFor(items,month){return items.filter((x)=>monthKey(x.fecha)===month).sort((a,b)=>a.fecha.localeCompare(b.fecha)||(a.createdAt||0)-(b.createdAt||0));}
function monthsFor(items){return [...new Set([monthKey(today()),...items.map((x)=>monthKey(x.fecha))])].sort();}
function monthOptions(select,months,value){select.replaceChildren(...months.map((m)=>option(monthLabel(m),m)));select.value=value;}
function option(label,value,disabled=false){const node=document.createElement("option");node.textContent=label;node.value=value;node.disabled=disabled;node.selected=disabled;return node;}
function cell(value,label,cls=""){const node=document.createElement("td");node.dataset.label=label;node.className=cls;node.textContent=value;return node;}
function html(markup){const t=document.createElement("template");t.innerHTML=markup.trim();return t.content.firstElementChild;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function monthKey(date){return date.slice(0,7);}
function monthLabel(value){const [year,month]=value.split("-").map(Number);const text=new Intl.DateTimeFormat("es-AR",{month:"long",year:"numeric"}).format(new Date(year,month-1,1));return text[0].toUpperCase()+text.slice(1);}
function formatDate(value){const [year,month,day]=value.split("-").map(Number);return dateFormat.format(new Date(year,month-1,day));}
function norm(value){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/\s+/g," ");}
function amountTyping(value){const raw=value.replace(/[^\d,]/g,""),[int="",...dec]=raw.split(","),grouped=int.replace(/^0+(?=\d)/,"").replace(/\B(?=(\d{3})+(?!\d))/g,"."),fraction=dec.join("").slice(0,2);return raw.includes(",")?`${grouped||"0"},${fraction}`:grouped;}
function parseAmount(value){const n=value.replace(/\./g,"").replace(",",".");return /^\d+(?:\.\d{1,2})?$/.test(n)?Number(n):NaN;}
function amountForInput(value){return new Intl.NumberFormat("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);}
function error(input,message,text){input.setAttribute("aria-invalid","true");message.textContent=text;input.focus();}
function clearError(input,message){input.removeAttribute("aria-invalid");message.textContent="";}
function writeError(input,message){error(input,message,"No se pudo guardar. Revisá tu conexión e intentá de nuevo.");}
function confirmAction(message, label) { return new Promise((resolve) => { el.confirmDescription.textContent = message; el.confirmAccept.textContent = label; const close = (value) => { el.confirmAccept.onclick = null; el.confirmCancel.onclick = null; if (el.confirmDialog.open) el.confirmDialog.close(); resolve(value); }; el.confirmAccept.onclick = () => close(true); el.confirmCancel.onclick = () => close(false); el.confirmDialog.showModal(); }); }
